site_name: mmm-eval
site_description: Open-source evaluation of marketing mix model (MMM) performance
site_author: mmm-eval Contributors
site_url: https://mutinex.github.io/mmm-eval/

# Repository
repo_name: mutinex/mmm-eval
repo_url: https://github.com/mutinex/mmm-eval
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2025 mmm-eval Contributors

# Theme
theme:
  name: material
  language: en
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.instant.result
    - navigation.instant.suggest
    - navigation.instant.tracking
    - navigation.instant.worker
    - navigation.managing
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - navigation.tracking.attribution
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
  logo: assets/logo.png
  favicon: assets/favicon.png

# Navigation
nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
    - Configuration: getting-started/configuration.md
  - User Guide:
    - Command Line Interface: user-guide/cli.md
    - Frameworks: user-guide/frameworks.md
    - Tests: user-guide/tests.md
    - Metrics: user-guide/metrics.md
    - Data: user-guide/data.md
  - API Reference:
    - Adapters: api/adapters.md
    - Core: api/core.md
    - CLI: api/cli.md
    - Data: api/data.md
    - Metrics: api/metrics.md
  - Examples:
    - Basic Usage: examples/basic-usage.md
  - Development:
    - Contributing: development/contributing.md
    - Development Setup: development/setup.md
    - Testing: development/testing.md
  - About:
    - License: about/license.md

# Plugins
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: true
            show_submodules: true
            show_signature_annotations: true
            show_bases: true
            show_root_heading: true
            show_root_toc_entry: true
            show_category_heading: true
            show_if_no_docstring: false
            docstring_style: google
            docstring_section_style: table
            preload_modules: [mmm_eval, mmm_eval.core, mmm_eval.data, mmm_eval.metrics, mmm_eval.adapters, mmm_eval.cli]
            filters: ["!^_"]
            merge_init_into_class: true
            show_signature: true
  - git-revision-date-localized:
      enable_creation_date: true
  - minify:
      minify_html: true

# Markdown extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Extra CSS and JS
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Extra
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mutinex/mmm-eval
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/mutinex
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY

# Validation
validation:
  nav:
    omitted_files: ignore
  not_found: warn 