[tool.poetry]
name = "mmm-eval"
version = "0.1.0"
description = "A simple and powerful evaluation package for machine learning models"
authors = ["Your Name <your.email@example.com>"]
maintainers = ["Your Name <your.email@example.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/yourusername/mmm-eval"
repository = "https://github.com/yourusername/mmm-eval"
documentation = "https://mmm-eval.readthedocs.io/"
keywords = ["evaluation", "machine learning", "metrics"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
packages = [{include = "mmm_eval", from = "src"}]

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.20.0"
pandas = "^1.3.0"

[tool.poetry.group.dev.dependencies]
pytest = "^6.0"
pytest-cov = "^2.0"
black = "^22.0"
isort = "^5.0"
flake8 = "^4.0"
mypy = "^0.900"
pre-commit = "^2.0"

[tool.poetry.group.docs.dependencies]
sphinx = "^4.0"
sphinx-rtd-theme = "^1.0"
myst-parser = "^0.17"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/yourusername/mmm-eval/issues"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ['py38']

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = "--cov=mmm_eval --cov-report=term-missing --cov-report=html"

[tool.mypy]
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true 